### PR TITLE
Make EnvironmentInfoCollector working on Mono.

### LINKED ISSUE #20: EnvironmentInfoCollector in Exceptionless.Extras throws Exceptions on Mono
On my test maschine (Ubuntu 14.04) i first had to install: libmono-microsoft-visualbasic11.0-cil

otherwise:

>System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.VisualBasic, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

after installing the related package i got:

> EnvironmentInfoCollector: Unable to get physical memory. Error message: The requested feature is not implemented. 
EnvironmentInfoCollector: Unable to get process id. Error message: GetCurrentProcessId 
EnvironmentInfoCollector: Unable to get process name. Error message: GetModuleHandle 
EnvironmentInfoCollector: Unable to get thread id. Error message: GetCurrentThreadId

The problem is, that in ```Microsoft.VisualBasic.Devices``` the needed methods are not implemented:

See: https://github.com/mono/mono-basic/blob/master/vbruntime/Microsoft.VisualBasic/Microsoft.VisualBasic.Devices/ComputerInfo.vb

The report still works, but you will see reported errors in your log file.

### PR DESCRIPTION
**Pull request by bitbeans**
- Fixes #20.

>Note: info.AvailablePhysicalMemory will only work on mono 4.0+

### CODE REVIEW

File: Source/Extras/Services/EnvironmentInfoCollector.cs [hunk 1]
```diff
@@ -43,10 +44,24 @@ public class EnvironmentInfoCollector : IEnvironmentInfoCollector {
             }
 
             try {
-                if (computerInfo != null)
-                    info.TotalPhysicalMemory = Convert.ToInt64(computerInfo.TotalPhysicalMemory);
-                if (computerInfo != null)
-                    info.AvailablePhysicalMemory = Convert.ToInt64(computerInfo.AvailablePhysicalMemory);
+                if (EnvironmentHelper.IsUnix)
```
Comment (niemyjski) [inline Source/Extras/Services/EnvironmentInfoCollector.cs]: Can we move this check into this file as a private property.

File: Source/Extras/Services/EnvironmentInfoCollector.cs [hunk 2]
```diff
@@ -43,10 +44,24 @@ public class EnvironmentInfoCollector : IEnvironmentInfoCollector {
...
+                        //https://github.com/mono/mono/blob/f0834d5407f492a2a21e2f62f8f8c418d64ba6fa/mono/metadata/mono-perfcounters-def.h
+                        var performanceCounterTotalPhysicalMemory = new PerformanceCounter("Mono Memory", "Total Physical Memory");
+                        var performanceCounterAvailablePhysicalMemory = new PerformanceCounter("Mono Memory", "Available Physical Memory"); //mono 4.0+
+                        info.TotalPhysicalMemory = Convert.ToInt64(performanceCounterTotalPhysicalMemory.RawValue);
+                        info.AvailablePhysicalMemory = Convert.ToInt64(performanceCounterAvailablePhysicalMemory.RawValue);
+                    }
+                }
+                else
+                {
+                    if (computerInfo != null)
```
Comment (niemyjski) [inline Source/Extras/Services/EnvironmentInfoCollector.cs]: Can we join these into one null check

File: Source/Extras/Services/EnvironmentInfoCollector.cs [hunk 3]
```diff
@@ -85,19 +100,42 @@ public class EnvironmentInfoCollector : IEnvironmentInfoCollector {
...
+                }
             } catch (Exception ex) {
                 _log.FormattedInfo(typeof(EnvironmentInfoCollector), "Unable to get process name. Error message: {0}", ex.Message);
             }
 
             try {
-                info.ThreadId = KernelNativeMethods.GetCurrentThreadId().ToString(NumberFormatInfo.InvariantInfo);
+                if (EnvironmentHelper.IsUnix)
+                {
+                    info.ThreadId = System.Threading.Thread.CurrentThread.ManagedThreadId.ToString();
```
Comment (niemyjski) [inline Source/Extras/Services/EnvironmentInfoCollector.cs]: I noticed below we are passing (NumberFormatInfo.InvariantInfo) to the ToString overload. I think we should do the same here.

File: Source/Extras/Services/EnvironmentInfoCollector.cs [hunk 4]
```diff
@@ -43,10 +44,24 @@ public class EnvironmentInfoCollector : IEnvironmentInfoCollector {
...
-                if (computerInfo != null)
-                    info.TotalPhysicalMemory = Convert.ToInt64(computerInfo.TotalPhysicalMemory);
-                if (computerInfo != null)
-                    info.AvailablePhysicalMemory = Convert.ToInt64(computerInfo.AvailablePhysicalMemory);
+                if (EnvironmentHelper.IsUnix)
+                {
+                    if (PerformanceCounterCategory.Exists("Mono Memory"))
+                    {
+                        //https://github.com/mono/mono/blob/f0834d5407f492a2a21e2f62f8f8c418d64ba6fa/mono/metadata/mono-perfcounters-def.h
+                        var performanceCounterTotalPhysicalMemory = new PerformanceCounter("Mono Memory", "Total Physical Memory");
```
Comment (niemyjski) [inline Source/Extras/Services/EnvironmentInfoCollector.cs]: Can we shorten the name of this and get rid of performanceCounter in the name (also I'd move the comment to the commit description.
